---
title: "Developing Backtesting Systematic Trading Strategies"
output: html_document
date: November 29, 2014
author: Brian G. Peterson
---

# Developing Backtesting Systematic Trading Strategies
# Разработка и тестирование стратегий системной торговли
## Brian G. Peterson
## November 29, 2014

Аналитики и портфельные менеджеры почтоянно сталкиваются с многочисленными трудностями при разработке новых торговых систем. Эта статья рассматривает детальное, воспроизводимое описание процесса поиска новых идей, разработки гипотез на основе этих идей, проверки результатов различными способами, а также измерение и уменьшение влияния рисков переобучения.

> Бэктестинг.  Я ненавижу его -  это же просто оптимизация на истории. Вы никогда не увидите плохой резульатат на тестировании. Никогда! На любой стратегии. - [Josh Diedesch (2014)](http://www.ai-cio.com/channel/RISK-MANAGEMENT/The-Backtesting-Crisis/)

## Ограничения, Критерии и цели

> На самом деле, все модели неверны, но некоторые из них полезны. -George Box(1987)

Прежде чем вы начнете что-то делать дальше, важно понять, чего именно вы пытаетесь достичь. Стратегии или бэктесты, созданные без четко определенных целей, будут несовместимы с реальными рыночными условиями и ограничениями (которые также нужно заранее формализировать). Хуже того, такой подход приведет к тому, что вашей основной целью станет повторить результат бэктеста, что в итоге может завершится неправильным принятием решений на основе переобучения на истории.


## Понимание возможностей и ограничений вашего торгового процесса

Прежде чем формулировать торговую гипотезу или писать спецификацию стратегии, сначала необходимо подумать о вашем торговом процессе. Какие существуют затраты, ограничения, какие у вас возможности и преимущества. Многие пропускают этот шаг, но вы потратитие время в пустую, разрабатываю стратегию, которую не сможете использовать.

Вот некоторые критерии, которые необходимы рассмотреть:

+ возможности торговой платформы
+ перечень доступных рынков
+ перечень финансовых интрументов
+ доступ к рыночным данным
+ инфраструктура
+ капитал
+ тарифы/издержки/скидки

## Выбор контрольных показателей

Определение контрольных показателей необходимо для оценки производительности и контроля рисков переобучения вашей системы. Менеджеры фондов используют стандартные системы показателей, как правило, построенные на биржевых индексах или индексных производных. Ваш бенчмарк должен учитывать особенности вашего торгового процесса и иметь достаточных набор контрольных показателей для оценки производительности вашей стратегии с течением времени.

## 
